/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

float *suma_1_svc(valores *argp, struct svc_req *rqstp) {
	static float  result;
	result = (float)argp->i + (float)argp->j;
	return &result;
}

float *resta_1_svc(valores *argp, struct svc_req *rqstp) {
	static float  result;
	result = (float)argp->i - (float)argp->j;
	return &result;
}

float *
multiplicacion_1_svc(valores *argp, struct svc_req *rqstp)
{
	static float  result;
	result = (float)argp->i * (float)argp->j;
	return &result;
}

float *division_1_svc(valores *argp, struct svc_req *rqstp) {
	static float  result;
	if (argp->j != 0) {
           result = (float)argp->i / (float)argp->j;
    	} else {
           printf("Error: Division by zero\n");
    	}
	return &result;
}
